table Customer
	lineageTag: e4f5a6b7-c8d9-0123-ef01-234567890123

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 1a2b3c4d-5e6f-7890-ab01-234567890abc
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 2b3c4d5e-6f7a-8901-bc12-34567890abcd
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 3c4d5e6f-7a8b-9012-cd23-4567890abcde
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column CompanyName
		dataType: string
		lineageTag: 4d5e6f7a-8b9c-0123-de34-567890abcdef
		summarizeBy: none
		sourceColumn: CompanyName

		annotation SummarizationSetBy = Automatic

	column EmailAddress
		dataType: string
		lineageTag: 5e6f7a8b-9c0d-1234-ef45-67890abcdef0
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: 6f7a8b9c-0d1e-2345-f056-7890abcdef01
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 7a8b9c0d-1e2f-3456-0167-890abcdef012
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column StateProvince
		dataType: string
		lineageTag: 8b9c0d1e-2f3a-4567-1278-90abcdef0123
		summarizeBy: none
		sourceColumn: StateProvince

		annotation SummarizationSetBy = Automatic

	column CountryRegion
		dataType: string
		lineageTag: 9c0d1e2f-3a4b-5678-2389-0abcdef01234
		summarizeBy: none
		sourceColumn: CountryRegion

		annotation SummarizationSetBy = Automatic

	measure CustomerCount = DISTINCTCOUNT(Customer[CustomerID])
		formatString: 0
		lineageTag: ad1e2f3a-4b5c-6789-34ab-cdef01234567

	partition Customer = entity
		mode: directLake
		source
			entityName: 'Customer'
			schemaName: 'dbo'
			expressionSource: DatabaseQuery

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
