table Product
	lineageTag: d3e4f5a6-b7c8-9012-def0-234567890123

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: aabb1122-3344-5566-7788-99aabbccddee
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: bbcc2233-4455-6677-8899-aabbccddeeff
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column ProductNumber
		dataType: string
		lineageTag: ccdd3344-5566-7788-99aa-bbccddeeff00
		summarizeBy: none
		sourceColumn: ProductNumber

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: ddee4455-6677-8899-aabb-ccddeeff0011
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column ListPrice
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: eeff5566-7788-99aa-bbcc-ddeeff001122
		summarizeBy: sum
		sourceColumn: ListPrice

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column StandardCost
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ff006677-8899-aabb-ccdd-eeff00112233
		summarizeBy: sum
		sourceColumn: StandardCost

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ProductCategoryID
		dataType: int64
		formatString: 0
		lineageTag: 00117788-99aa-bbcc-ddee-ff0011223344
		summarizeBy: none
		sourceColumn: ProductCategoryID

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		source =
			let
			    Source = Table.FromRows(
			        {
			            {680, "HL Road Frame - Black, 58",   "FR-R92B-58", "Black",  1059.3100, 1431.50, 2},
			            {706, "HL Road Frame - Red, 58",     "FR-R92R-58", "Red",    1059.3100, 1431.50, 2},
			            {707, "Sport-100 Helmet, Red",       "HL-U509-R",  "Red",      13.0863,   34.99, 4},
			            {708, "Sport-100 Helmet, Black",     "HL-U509",    "Black",    13.0863,   34.99, 4},
			            {709, "Mountain Bike Socks, M",      "SO-B909-M",  "White",     3.3963,    9.50, 3},
			            {710, "Mountain Bike Socks, L",      "SO-B909-L",  "White",     3.3963,    9.50, 3},
			            {711, "Sport-100 Helmet, Blue",      "HL-U509-B",  "Blue",     13.0863,   34.99, 4},
			            {712, "AWC Logo Cap",                "CA-1098",    "Multi",     6.9223,    8.99, 3},
			            {713, "Long-Sleeve Logo Jersey, S",  "LJ-0192-S",  "Multi",    38.4923,   49.99, 3},
			            {714, "Long-Sleeve Logo Jersey, L",  "LJ-0192-L",  "Multi",    38.4923,   49.99, 3},
			            {715, "Long-Sleeve Logo Jersey, XL", "LJ-0192-X",  "Multi",    38.4923,   49.99, 3},
			            {716, "Road Frame - Red, 48",        "FR-R92R-48", "Red",     352.1544, 1431.50, 2},
			            {717, "Road Frame - Red, 44",        "FR-R92R-44", "Red",     352.1544, 1431.50, 2},
			            {718, "Mountain Frame - Black, 48",  "FR-M94B-48", "Black",   224.9501,  539.99, 1},
			            {722, "Mountain-200 Black, 38",      "BK-M68B-38", "Black",  1251.0000, 2319.99, 1}
			        },
			        type table [
			            ProductID         = Int64.Type,
			            Name              = text,
			            ProductNumber     = text,
			            Color             = text,
			            StandardCost      = Currency.Type,
			            ListPrice         = Currency.Type,
			            ProductCategoryID = Int64.Type
			        ]
			    )
			in
			    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
