table SalesOrderDetail
	lineageTag: c2d3e4f5-a6b7-8901-cdef-123456789012

	column SalesOrderID
		dataType: int64
		formatString: 0
		lineageTag: 11223344-5566-7788-99aa-bbccddeeff00
		summarizeBy: none
		sourceColumn: SalesOrderID

		annotation SummarizationSetBy = Automatic

	column SalesOrderDetailID
		dataType: int64
		formatString: 0
		lineageTag: 22334455-6677-8899-aabb-ccddeeff0011
		summarizeBy: none
		sourceColumn: SalesOrderDetailID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 33445566-7788-99aa-bbcc-ddeeff001122
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column OrderQty
		dataType: int64
		formatString: 0
		lineageTag: 44556677-8899-aabb-ccdd-eeff00112233
		summarizeBy: sum
		sourceColumn: OrderQty

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 55667788-99aa-bbcc-ddee-ff0011223344
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column UnitPriceDiscount
		dataType: decimal
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 66778899-aabb-ccdd-eeff-001122334455
		summarizeBy: none
		sourceColumn: UnitPriceDiscount

		annotation SummarizationSetBy = Automatic

	column LineTotal
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7799bbcc-ddee-ff00-1122-334455667788
		summarizeBy: sum
		sourceColumn: LineTotal

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure TotalLineAmount = SUMX(SalesOrderDetail, SalesOrderDetail[OrderQty] * SalesOrderDetail[UnitPrice] * (1 - SalesOrderDetail[UnitPriceDiscount]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7788aabb-ccdd-eeff-0011-223344556677

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition SalesOrderDetail = m
		mode: import
		source =
			let
			    Source = Table.FromRows(
			        {
			            { 1,  1, 722, 2, 2319.99, 0.00, 4639.98},
			            { 1,  2, 714, 3,   49.99, 0.00,  149.97},
			            { 1,  3, 707, 2,   34.99, 0.00,   69.98},
			            { 2,  4, 716, 1, 1431.50, 0.00, 1431.50},
			            { 2,  5, 707, 2,   34.99, 0.00,   69.98},
			            { 3,  6, 718, 1,  539.99, 0.00,  539.99},
			            { 4,  7, 716, 2, 1431.50, 0.00, 2863.00},
			            { 4,  8, 708, 1,   34.99, 0.00,   34.99},
			            { 5,  9, 709, 5,    9.50, 0.00,   47.50},
			            { 5, 10, 710, 5,    9.50, 0.00,   47.50},
			            { 6, 11, 714, 2,   49.99, 0.00,   99.98},
			            { 6, 12, 718, 1,  539.99, 0.05,  512.99},
			            { 7, 13, 722, 1, 2319.99, 0.00, 2319.99},
			            { 7, 14, 706, 1, 1431.50, 0.05, 1359.93},
			            { 7, 15, 711, 2,   34.99, 0.00,   69.98},
			            { 8, 16, 712, 5,    8.99, 0.05,   42.70},
			            { 8, 17, 709,10,    9.50, 0.10,   85.50},
			            { 9, 18, 716, 2, 1431.50, 0.00, 2863.00},
			            { 9, 19, 708, 2,   34.99, 0.05,   66.48},
			            {10, 20, 718, 1,  539.99, 0.00,  539.99},
			            {11, 21, 722, 2, 2319.99, 0.00, 4639.98},
			            {11, 22, 715, 3,   49.99, 0.00,  149.97},
			            {12, 23, 716, 2, 1431.50, 0.00, 2863.00},
			            {12, 24, 707, 2,   34.99, 0.00,   69.98},
			            {13, 25, 714, 2,   49.99, 0.00,   99.98},
			            {13, 26, 718, 1,  539.99, 0.05,  512.99},
			            {14, 27, 718, 1,  539.99, 0.00,  539.99},
			            {15, 28, 722, 1, 2319.99, 0.00, 2319.99},
			            {15, 29, 706, 1, 1431.50, 0.05, 1359.93},
			            {15, 30, 711, 2,   34.99, 0.05,   66.48},
			            {16, 31, 716, 1, 1431.50, 0.00, 1431.50},
			            {17, 32, 722, 1, 2319.99, 0.00, 2319.99},
			            {17, 33, 713, 1,   49.99, 0.00,   49.99},
			            {18, 34, 716, 1, 1431.50, 0.00, 1431.50},
			            {18, 35, 709, 5,    9.50, 0.00,   47.50},
			            {19, 36, 718, 1,  539.99, 0.00,  539.99},
			            {20, 37, 722, 2, 2319.99, 0.00, 4639.98},
			            {20, 38, 714, 3,   49.99, 0.05,  142.47},
			            {21, 39, 718, 1,  539.99, 0.05,  512.99},
			            {21, 40, 714, 2,   49.99, 0.00,   99.98},
			            {22, 41, 716, 2, 1431.50, 0.00, 2863.00},
			            {22, 42, 708, 1,   34.99, 0.05,   33.24},
			            {23, 43, 709, 5,    9.50, 0.05,   45.13},
			            {23, 44, 710, 5,    9.50, 0.05,   45.13},
			            {24, 45, 722, 1, 2319.99, 0.00, 2319.99},
			            {24, 46, 706, 1, 1431.50, 0.05, 1359.93},
			            {24, 47, 711, 2,   34.99, 0.00,   69.98},
			            {25, 48, 716, 1, 1431.50, 0.00, 1431.50},
			            {26, 49, 722, 1, 2319.99, 0.00, 2319.99},
			            {26, 50, 713, 1,   49.99, 0.00,   49.99},
			            {27, 51, 718, 1,  539.99, 0.00,  539.99},
			            {28, 52, 722, 2, 2319.99, 0.00, 4639.98},
			            {28, 53, 715, 3,   49.99, 0.05,  142.47},
			            {29, 54, 718, 1,  539.99, 0.05,  512.99},
			            {29, 55, 714, 2,   49.99, 0.00,   99.98},
			            {30, 56, 716, 2, 1431.50, 0.00, 2863.00},
			            {30, 57, 708, 1,   34.99, 0.05,   33.24}
			        },
			        type table [
			            SalesOrderID       = Int64.Type,
			            SalesOrderDetailID = Int64.Type,
			            ProductID          = Int64.Type,
			            OrderQty           = Int64.Type,
			            UnitPrice          = Currency.Type,
			            UnitPriceDiscount  = Currency.Type,
			            LineTotal          = Currency.Type
			        ]
			    )
			in
			    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
