table SalesOrderDetail
	lineageTag: c2d3e4f5-a6b7-8901-cdef-123456789012

	column SalesOrderID
		dataType: int64
		formatString: 0
		lineageTag: 11223344-5566-7788-99aa-bbccddeeff00
		summarizeBy: none
		sourceColumn: SalesOrderID

		annotation SummarizationSetBy = Automatic

	column SalesOrderDetailID
		dataType: int64
		formatString: 0
		lineageTag: 22334455-6677-8899-aabb-ccddeeff0011
		summarizeBy: none
		sourceColumn: SalesOrderDetailID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 33445566-7788-99aa-bbcc-ddeeff001122
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column OrderQty
		dataType: int64
		formatString: 0
		lineageTag: 44556677-8899-aabb-ccdd-eeff00112233
		summarizeBy: sum
		sourceColumn: OrderQty

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 55667788-99aa-bbcc-ddee-ff0011223344
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column UnitPriceDiscount
		dataType: decimal
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 66778899-aabb-ccdd-eeff-001122334455
		summarizeBy: none
		sourceColumn: UnitPriceDiscount

		annotation SummarizationSetBy = Automatic

	column LineTotal
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7799bbcc-ddee-ff00-1122-334455667788
		summarizeBy: sum
		sourceColumn: LineTotal

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure TotalLineAmount = SUMX(SalesOrderDetail, SalesOrderDetail[OrderQty] * SalesOrderDetail[UnitPrice] * (1 - SalesOrderDetail[UnitPriceDiscount]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7788aabb-ccdd-eeff-0011-223344556677

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition SalesOrderDetail = entity
		mode: directLake
		source
			entityName: 'SalesOrderDetail'
			schemaName: 'dbo'
			expressionSource: DatabaseQuery

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
