table SalesOrderHeader
	lineageTag: b1c2d3e4-f5a6-7890-bcde-f12345678901

	column SalesOrderID
		dataType: int64
		formatString: 0
		lineageTag: e1f2a3b4-c5d6-7890-ef01-234567890abc
		summarizeBy: none
		sourceColumn: SalesOrderID

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: f2a3b4c5-d6e7-8901-f012-34567890abcd
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: a3b4c5d6-e7f8-9012-0123-4567890abcde
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column SubTotal
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b4c5d6e7-f8a9-0123-1234-567890abcdef
		summarizeBy: sum
		sourceColumn: SubTotal

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column TaxAmt
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c5d6e7f8-a9b0-1234-2345-67890abcdef0
		summarizeBy: sum
		sourceColumn: TaxAmt

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Freight
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: d6e7f8a9-b0c1-2345-3456-7890abcdef01
		summarizeBy: sum
		sourceColumn: Freight

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Status
		dataType: int64
		formatString: 0
		lineageTag: e7f8a9b0-c1d2-3456-4567-890abcdef012
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column DueDate
		dataType: dateTime
		formatString: General Date
		lineageTag: b1c2d3e4-5f6a-7890-b0c1-d2e3f4a5b6c7
		summarizeBy: none
		sourceColumn: DueDate

		annotation SummarizationSetBy = Automatic

	column TotalDue
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c2d3e4f5-6a7b-8901-c1d2-e3f4a5b6c7d8
		summarizeBy: sum
		sourceColumn: TotalDue

		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column SalesTerritory
		dataType: string
		lineageTag: d3e4f5a6-7b8c-9012-d2e3-f4a5b6c7d8e9
		summarizeBy: none
		sourceColumn: SalesTerritory

		annotation SummarizationSetBy = Automatic

	measure TotalRevenue = SUM(SalesOrderHeader[SubTotal]) + SUM(SalesOrderHeader[TaxAmt]) + SUM(SalesOrderHeader[Freight])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: f8a9b0c1-d2e3-4567-5678-90abcdef0123

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure OrderCount = COUNTROWS(SalesOrderHeader)
		formatString: 0
		lineageTag: a9b0c1d2-e3f4-5678-6789-0abcdef01234

	measure AvgOrderValue = DIVIDE(SUM(SalesOrderHeader[SubTotal]), COUNTROWS(SalesOrderHeader))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ba0c1d2e-f3a4-6789-789a-bcdef0123456

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition SalesOrderHeader = entity
		mode: directLake
		source
			entityName: 'SalesOrderHeader'
			schemaName: 'dbo'
			expressionSource: DatabaseQuery

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
